import { useEffect, useState } from 'react'
import { ArrowUpRight, GitBranch as Github, Network as Linkedin, Mail, Menu, X, MapPin, Phone, Send, ExternalLink, Download, GraduationCap, Lightbulb, Rocket, BrainCircuit, Code2, ChartNoAxesCombined, PanelsTopLeft, Award, CalendarDays } from 'lucide-react'
import { certificates, profile, projects, skills } from './data'

const iconMap = { Code2, ChartNoAxesCombined, BrainCircuit, PanelsTopLeft, Lightbulb }

function useReveal() {
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('visible')), { threshold: 0.12 })
    document.querySelectorAll('.reveal').forEach((element) => observer.observe(element))
    return () => observer.disconnect()
  }, [])
}

function Navbar() {
  const [open, setOpen] = useState(false)
  const links = ['Home', 'About', 'Skills', 'Projects', 'Certificates', 'Contact']
  const close = () => setOpen(false)
  return <header className="navbar"><div className="nav-inner"><a className="brand" href="#home" onClick={close}>TP<span>.</span></a><nav className={open ? 'nav-links open' : 'nav-links'}>{links.map((link) => <a key={link} href={`#${link.toLowerCase()}`} onClick={close}>{link}</a>)}<a className="nav-cta" href="#contact" onClick={close}>Let's connect <ArrowUpRight size={16} /></a></nav><button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div></header>
}

function Hero() {
  return <section id="home" className="hero"><div className="hero-grid" /><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><div className="container hero-content"><div className="hero-copy reveal"><p className="eyebrow"><span className="status-dot" /> Available for opportunities</p><h1>Curious mind.<br /><em>Data-driven</em> future.</h1><p className="hero-intro">Hi, I'm <strong>T Pallavi</strong>, an aspiring AI & Data Science student passionate about building technology-driven solutions, exploring data, and turning ideas into meaningful projects.</p><div className="hero-actions"><a className="button button-primary" href="#projects">View my projects <ArrowUpRight size={17} /></a><a className="button button-ghost" href="/T-Pallavi-Resume.pdf" download>Download resume <Download size={16} /></a></div><div className="socials"><a href={profile.linkedin} aria-label="LinkedIn placeholder"><Linkedin size={18} /></a><a href={profile.github} aria-label="GitHub placeholder"><Github size={18} /></a><a href={`mailto:${profile.email}`} aria-label="Send email"><Mail size={18} /></a><span className="social-line" /><span>Based in Bengaluru</span></div></div><div className="hero-aside reveal"><div className="hero-index">01 <span>/ 04</span></div><div className="hero-stamp"><div className="stamp-ring">✦</div><span>Learning<br />in public</span></div><div className="hero-note">Currently exploring<br /><b>Python · IoT · AI</b></div></div></div><a className="scroll-cue" href="#about">Scroll to explore <span>↓</span></a></section>
}

function SectionIntro({ kicker, title, text, id }) { return <div className="section-intro reveal"><p className="kicker">{kicker}</p><h2 id={id}>{title}</h2>{text && <p className="section-lead">{text}</p>}</div> }

function About() {
  const cards = [{ icon: GraduationCap, title: 'Education', text: '2nd Year AI & Data Science' }, { icon: MapPin, title: 'University', text: 'Reva University, Bengaluru' }, { icon: Lightbulb, title: 'Interests', text: 'AI · Data Science · IoT · Technology' }, { icon: Rocket, title: 'Focus', text: 'Learning · Building · Problem Solving' }]
  return <section id="about" className="section about"><div className="container"><SectionIntro kicker="01 — About me" title={<>A student who likes to<br /><em>make things matter.</em></>} text="I am a second-year Artificial Intelligence and Data Science student at Reva University, Bengaluru. I am developing my skills in programming, Python, data science, IoT, and problem solving. I enjoy working on practical projects that combine technology with real-world applications." id="about-heading" /><div className="info-grid">{cards.map(({ icon: Icon, title, text }, index) => <article className="info-card reveal" style={{ '--delay': `${index * 80}ms` }} key={title}><Icon size={22} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
}

function Skills() { return <section id="skills" className="section skills"><div className="container"><SectionIntro kicker="02 — Capabilities" title={<>Tools for a<br /><em>better question.</em></>} text="A growing toolkit shaped by curiosity, coursework, and hands-on building." id="skills-heading" /><div className="skills-grid">{skills.map((skill, index) => { const Icon = iconMap[skill.icon]; return <article className="skill-card reveal" style={{ '--delay': `${index * 70}ms` }} key={skill.title}><div className="skill-top"><span className="skill-number">0{index + 1}</span><Icon size={21} /></div><h3>{skill.title}</h3><div className="skill-tags">{skill.items.map((item) => <span key={item}>{item}</span>)}</div></article> })}</div></div></section> }

function Projects() { return <section id="projects" className="section projects"><div className="container"><SectionIntro kicker="03 — Selected work" title={<>Ideas, turned into<br /><em>something tangible.</em></>} text="Early projects are where I learn to connect technical possibility with human problems." id="projects-heading" /><div className="project-list">{projects.map((project, index) => <article className={`project-card ${project.accent} reveal`} key={project.title}><div className="project-art"><span className="project-number">{project.number}</span><div className="art-lines" /><div className="art-symbol">{index === 0 ? '⌁' : '◌'}</div><span className="art-label">{project.category}</span></div><div className="project-body"><p className="kicker">{project.category}</p><h3>{project.title}</h3><p>{project.description}</p><div className="project-tags">{project.technologies.map((technology) => <span key={technology}>{technology}</span>)}</div><div className="project-links"><a href="#contact">View project <ArrowUpRight size={16} /></a><a href={profile.github}>GitHub <Github size={15} /></a></div></div></article>)}</div></div></section> }

function Certificates() { const [selected, setSelected] = useState(null); return <section id="certificates" className="section certificates"><div className="container"><SectionIntro kicker="04 — Certifications" title={<>Proof of a<br /><em>hungry learner.</em></>} text="A record of courses and programs that have expanded how I think, build, and solve." id="certificates-heading" /><div className="certificate-grid">{certificates.map((certificate, index) => <button className={`certificate-card ${certificate.tone} reveal`} style={{ '--delay': `${index * 60}ms` }} key={certificate.title} onClick={() => setSelected(certificate)}><div className="certificate-image"><img src={certificate.image} alt={`${certificate.title} certificate`} onError={(event) => { event.currentTarget.style.display = 'none'; event.currentTarget.parentElement.classList.add('image-missing') }} /><span>Certificate {String(index + 1).padStart(2, '0')}</span></div><div className="certificate-copy"><h3>{certificate.title}</h3><p>{certificate.organization}</p><small>{certificate.meta}</small></div><ExternalLink size={17} /></button>)}</div></div>{selected && <div className="modal-backdrop" role="presentation" onClick={() => setSelected(null)}><div className="certificate-modal" role="dialog" aria-modal="true" aria-label={selected.title} onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close certificate preview"><X /></button><div className={`modal-image ${selected.tone}`}><img src={selected.image} alt={`${selected.title} enlarged certificate`} onError={(event) => { event.currentTarget.style.display = 'none'; event.currentTarget.parentElement.classList.add('image-missing') }} /><span>Certificate image will appear here</span></div><p className="kicker">{selected.organization}</p><h3>{selected.title}</h3><p>{selected.meta}</p></div></div>}</section> }

function Achievements() { return <section className="achievements"><div className="container achievement-row"><div><p className="kicker">Milestones so far</p><h2>Small steps.<br /><em>Real momentum.</em></h2></div><div className="achievement-items"><p><Award size={20} /> Multiple IBM Skills Network courses in Python and Data Science</p><p><CalendarDays size={20} /> 42 hours of entrepreneurship coursework</p><p><Rocket size={20} /> Wadhwani Global Entrepreneur's Ignite Full program</p></div></div></section> }

function Education() { return <section className="section education"><div className="container education-layout"><SectionIntro kicker="05 — Education" title={<>Building the<br /><em>foundation.</em></>} id="education-heading" /><div className="timeline reveal"><div className="timeline-dot" /><p className="kicker">Currently pursuing</p><h3>Reva University, Bengaluru</h3><p className="degree">Artificial Intelligence & Data Science · 2nd Year</p><p>Currently pursuing my undergraduate studies and developing skills across programming, AI, data science, and technology.</p></div></div></section> }

function Contact() { const [sent, setSent] = useState(false); const submit = (event) => { event.preventDefault(); setSent(true); event.currentTarget.reset() }; return <section id="contact" className="section contact"><div className="container contact-layout"><div className="contact-copy"><SectionIntro kicker="06 — Contact" title={<>Let's build<br /><em>something together.</em></>} text="I'm always interested in learning, collaborating, and working on meaningful technology projects." id="contact-heading" /><div className="contact-details"><a href={`mailto:${profile.email}`}><Mail size={19} /><span>{profile.email}</span></a><a href={`tel:${profile.phone.replaceAll(' ', '')}`}><Phone size={19} /><span>{profile.phone}</span></a></div></div><form className="contact-form reveal" onSubmit={submit}><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label><label>Message<textarea required name="message" rows="4" placeholder="Tell me a little about your idea..." /></label><button className="button button-primary" type="submit">{sent ? 'Message ready to send' : 'Send message'} <Send size={16} /></button>{sent && <p className="success-message" role="status">Thanks, your message has been noted. Please send it through your email client.</p>}</form></div></section> }

function Footer() { return <footer className="footer"><div className="container footer-row"><div><a className="brand" href="#home">TP<span>.</span></a><p>Artificial Intelligence & Data Science Student</p></div><p>Built with React.js · © 2026 T Pallavi</p><div className="footer-socials"><a href={profile.github} aria-label="GitHub placeholder"><Github /></a><a href={profile.linkedin} aria-label="LinkedIn placeholder"><Linkedin /></a><a href={`mailto:${profile.email}`} aria-label="Email"><Mail /></a></div></div></footer> }

export default function App() { useReveal(); return <><Navbar /><main><Hero /><About /><Skills /><Projects /><Certificates /><Achievements /><Education /><Contact /></main><Footer /></> }
